### ISSUE TITLE
US1 - Create a cat list 

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#1]
## Value proposition

As a cat owner/ user,
I want all my registered cats displayed,
so that I have an overview of all my cats.

## Description

![Bildschirmfoto 2023-08-13 um 09 42 58](https://github.com/JanaS87/capstone-project/assets/136725332/29bca4e4-af62-4eae-b367-d36f2201feec)

## Acceptance criteria

- [x] list all cats as a card
- [x] every item has the same measure
- [x] the whole cat-name is visible
- [x] the page is vertically scrollable
- [x] the respective cat name is clearly displayed on the individual card

## Tasks

- [x] create a new branch feat/cat-list
- [x] create a file "db.js" with an array named "cats"
- [x] create new component for CatList
- [x] create new component for listItem Cat
- [x] map over the array of cats and display them in a card for every cat
- [x] add styling (size, colors, shadows...)
- [x] page can only be scrolled vertically if there are more entries
- [x] _optional_ test that all items are correctly displayed
