### ISSUE TITLE
US7 - Edit Cat Profile

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#10]
## Value proposition

As a cat owner/user, 
I want to have an editable cat profile, 
so I can change some information if necessary.

## Description

![Edit Cat Profile](https://github.com/JanaS87/capstone-project/assets/136725332/8d30c13b-3218-4121-af12-ae852644f94b)

## Acceptance criteria

_Cat Profile_
- [x] the information is only customizable after the edit button has been clicked
- [x] the edit button opens a new page in which the information can be edited

_Edit Page_
- [ ] every information, except the name, is customizable
- [ ] all fields, but the name itself, are clickable
- [ ] every checkbox can be checked and unchecked
- [ ] the save- button saves the changes
- [ ] with the remove cat button the whole cat profile can be removed
- [ ] when removing the cat, a modal opens to ask if this decision is correct (yes/ no)
- [ ] the drop down menu - buttons deletes or adds the cat food 
- [ ] if there is nothing to be changed, clicking the back button leads back to the cat profile
- [ ] saving the cat changes opens a modal with “Your cat is know updated”
- [ ] pressing the “okay” button from the saving modal leads back to the cat profile with the updated information

## Tasks

_Edit Page_
- [x] create a new branch feat/cat-profile-edit
- [x] create new folder “Update”
- [x] add  “[id].js” for the “edit cat page”
- [x] apply the form component for the cat editing
- [ ] create the delete button to remove the cat food
- [ ] create the button to remove the cat
- [x] create the save button
- [x] add styling

_Cat Profile Page_ 
- [x] get the edit button working with onClick

_Edit Modal_
- [ ] create a new component named “Modal.js”
- [ ] apply the modal component to the edit cat page
- [ ] apply the needed content to the modal component in the  edit cat page
- [ ] create the “are you sure” modal for the remove button
- [ ] create the “okay” button for the “cat updated” modal
- [ ] add router.push("/") the okay button

**Comment by JanaS87** [comment]
Need to take some tasks out for functionality.

Modal and DeleteCat will be getting a new US.
