### ISSUE TITLE
US10 - Edit Food Profile

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#11]
## Value proposition

As a cat owner/user, 
I want to have an editable cat food profile,
 so I can customize my cats personal food preferences.

## Description

![Edit Food profile](https://github.com/JanaS87/capstone-project/assets/136725332/1d03de2b-78ce-4f17-bd0b-28730085a82f)

## Acceptance criteria

_Food Profile Page_
- [ ] the edit button leads to the edit page

_Food Edit Page_
- [ ] the drop down menu is clickable
- [ ] the cats can be selected
- [ ] the add button adds the cat
- [ ] the added cat is visible below the drop down menu
- [ ] the “X” button removes the cat
- [ ] the side is only vertically scrollable
- [ ] the save button saves the changes that were made
- [ ] going back to the food profile, the changes are still visible
- [ ] the back button leads back to the food profile

## Tasks

_Food Detail Page_
- [x] create new branch named “feat/edit-food-page
- [ ] add edit button and set its routing to the edit page

Edit Food Page
- [ ] add new folder “FoodUpdates)
- [ ] add file “[id].js to the folder
- [ ] add drop down menus for both food categories
- [ ] set the map() for the cat names
- [ ] add the needed buttons (add/X/save)
- [ ] add functionality to the add / remove buttons with onClick()
- [ ] add functionality to the save button with onClick
