### ISSUE TITLE
US9 - Local Storage (refactoring part 1)

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#15]
## Value proposition

As a cat owner/user,
 I want all my changes to be saved, 
so I can  still see  all my changes after refreshing the page.

## Description

There is no picture for this US. 
The main thing is to restructure the code in such a 
way that all entries/changes made by yourself are saved.

## Acceptance criteria

Add new cat
- [ ] the save button saves the cat permanently

Cat overview
- [ ] refreshing the page won´t reset the cat overview

Edit Cat 
- [ ] every adjustment is saved permanently

Edit cat food
- [ ] every adjustment is saved permanently

## Tasks

- [ ] create new branch named "refactor/local-storage" (or something similar)
- [ ] import useLocalStorageState
- [ ] find every page where the useState() needs to be changed into useLocalStorageState()
- [ ] do the needed code adjustments like setting defaultValue for the States

**Comment by mariusgolabski** [comment]
LGTM
