### ISSUE TITLE
US11 - Food recommendations

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#16]
## Value proposition

As a cat owner/ user,
I would like to know if there are any cat food recommendations,
so that I know which cat food is best suited to my cat's health issues.

## Description

![recommended food](https://github.com/JanaS87/capstone-project/assets/136725332/458dac89-7729-45d1-b6d6-bd658df44a8a)

## Acceptance criteria

Generally
- [ ] the recommendations are below the cat profile
- [ ] at first there are the recommendations for the cat
- [ ] under the recommendations you find the food which is not good for your cat

recommended food / not recommended food
- [ ] every food is clickable and leads to the food detail page

### Note: 
I could set the color of the recommend- heading to green 
and not recommend- heading to red, but I´m not sure, yet.

## Tasks

- [x] create new branch named “feat/recommendations
- [ ] declare const “getRecommendedFood”
- [ ] declare const “healthIssues”
- [x] declare const “healthFilteredFood”
- [x] writing the logic to filter the food in relation to the health issues
- [ ] set the Link for the clickable cat food

### Note:
I am considering whether it would make sense to list the "harmful" ingredients as a tag so that you can immediately see what's inside. If I do so, it would be set in another US.

**Comment by JanaS87** [comment]
In the first step, the recommendations will be placed under the cat informations.
In the second step it will be outsourced to its own page. (US11)

**Comment by mariusgolabski** [comment]
Overall, it seems like a solid user story that sets a clear direction for the implementation process :thumbsup:
