### ISSUE TITLE
US12 - Cat and Recommend Tabs

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#17]
## Value proposition

As a cat owner/ user,
I would like to have a clean overview for the information about my cat and the recommended food,
so I can switch between both views.

## Description

![CatRecommendTab](https://github.com/JanaS87/capstone-project/assets/136725332/6a8292e3-2004-4f27-9967-f84159b41bc8)

## Acceptance criteria

Generally
- [ ] the active tab- paw is orange-colored
- [ ] the inactive tab-paw is black-colored

Cat profile page
- [ ] both tabs works properly 
- [ ] the Cat-Tab (starting point) leads to the cat profile
- [ ] the  Recommend- Tab leads to the food recommendations

Recommend page
- [ ] the cat food is clickable and leads to its respective detail page
- [ ] every food name is clearly readable and visible
- [ ] if there is a lot of content, the scrollbar is vertically scrollable
- [ ] recommended Food is green- colored
- [ ] not recommended Food is red- colored
- [ ] the “bad” ingredient is marked as a red tag

## Tasks

- [x] create branch named “feat/tab-recommend-page
- [x] create new component “Tabs”
- [x] create new component “Tab”
- [ ] create a new component for the bad- ingredient named “ingredientTags”
- [x] create new page “recommend”
- [x] add paw-icon from fontawesome in black and orange
- [x] set up the logic for the tabs
- [x] get the whole recommend- code  outsourced to its own page
- [x] implement the tabs on the cat detail page and the recommend page
- [x] set up the Link- route for both tabs
- [x] add the Link-route to the cat foods
- [x] add filter() -logic for the recommended cat foods, so it shows only the “good” food
- [x] add filter() -logic for the non-recommended cat foods, so it shows only the “bad” food
- [x] add styling

Food Detail Page
- [x] set up the back- button for 2 destinations with router.query.from

**Comment by alper92** [comment]
lgtm!
