### ISSUE TITLE
New US8 - Removing Cat

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#19]
## Value proposition

As a cat owner, 
I would like to have a button to remove an existing cat profile, 
so I can delete the relevant profile when I no longer need it.

## Description

![remove cat](https://github.com/JanaS87/capstone-project/assets/136725332/9ac44db7-7c22-4f10-8d21-dc440c0f11da)

## Acceptance criteria

Cat Edit Page

- [ ] the remove button is clearly visible
- [ ] clicking on the button opens a modal
- [ ] accepting the modal will remove the cat

Modal

- [ ] there is a message “Do you really want to remove this cat?”
- [ ] there are two buttons, “yes (red)” and “no (green)”
- [ ] “yes” will remove the cat and you get the message “cat successfully removed”
- [ ] removing the cat will lead to the cat overview
- [ ] “no” leads back to the edit page

## Tasks

Edit Cat Page

- [x] create a new branch feat/cat-remove
- [x] create the button to remove the cat
- [x] add styling

Modal

- [ ] create a new component named “Modal.js”
- [ ] apply the modal component to the edit cat page
- [ ] apply the needed content to the modal component in the  edit cat page
- [ ] create the “are you sure” modal for the remove button
- [x] create a “toast” for the “successfully removed” message
- [x] add router.push(“/”) so it leads back to the cat overview

**Comment by F-Kirchhoff** [comment]
Hey Jana, 
looks good to me, you can start working on it. If you want, you don't need to creat a modal for that functionality, there is a browser function called "confirm" that will work exactly the same (just not that beautiful). it is similar to "alert" which we already used. You can learn more about it on MDN if you want.
