### ISSUE TITLE
US 2 - cat profile

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#2]
## Value proposition

As a cat owner/user, 
I would like to have all the important details about my cat displayed,
so I can see everything directly at a glance.

## Description

![Image](https://github.com/JanaS87/capstone-project/assets/136725332/d239e9fc-c699-4816-b0fb-b01ed590a926)

## Acceptance criteria

Cat profile
- [x] shows all information about the cat
- [x] every information is fully readable
- [x] the page is vertically scrollable
- [ ] the good and bad acceptance food will be displayed as a list
- [x] the back-button leads back to the cat-overview

## Tasks
Cat profile
- [x] create a new branch feat/cat-profile
- [x] create new component Button
- [x] create a new page named CatProfile
- [ ] create a label "age"
- [ ] create an input field for the age
- [ ] add and set dynamic routing with <Link/> on the overview and the CatProfile page
- [ ] set textarea to “readonly”
- [ ] set input field to “readonly”
- [x] create back button with the needed routing to the overview page
- [x] add styling

**Comment by milodevhh** [comment]
Hey Jana, you describe it in perfect detail. Where will the "drop down menu" shown you mentioned in the task?
