### ISSUE TITLE
US14 - Fake-Login

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#21]
## Value proposition

As a cat owner/user, 
I would like to have the option to log in, 
so that only I have access to my data.

## Description

![Fake-Login](https://github.com/JanaS87/capstone-project/assets/136725332/4db9162c-a899-4837-8f01-1ef0ac350a7d)

## Acceptance criteria

- [ ] clearly visible and readable Logo
- [ ] themed background image
- [ ] the input fields are clickable and you can enter your login- data
- [ ] a visible, themed login button
- [ ] when the login- data is correct, the button leads to the cat overview

## Tasks

- [x] create new branch named “feat/fake-login
- [x] create login page
- [x] add everything that is needed (button, input fields,  background-image, Logo)
- [x] set the logic for the fake login (useState())
- [x] add functionality to the button
- [x] adjust the input field attributes/values
- [ ] add login success- message
- [x] add router.push() to lead to the overview
- [x] add logout-field
- [x] add styling

**Comment by mariusgolabski** [comment]
LGTM 👍
