### ISSUE TITLE
US13 - Refactoring - Styling Edition

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#22]
## Value proposition

As a cat owner/ user,
I would like to have a modern, minimalist appearance for my app, 
so that I have a better experience and the colors and the overview are not so stressful.

## Description

Just fixing some styling problems and setting up a nice look for my app.

## Acceptance criteria

- [ ] everything works as expected after the overhaul.

## Tasks

- [ ] create a branch "ref/styling"
- [ ] style everything that needs an overhaul (background, buttons, lists (list items) etc.)

**Comment by F-Kirchhoff** [comment]
LGTM
