### ISSUE TITLE
US15 - Refactoring - Outsourcing and Reducing 

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#23]
## Value proposition

As a Developer,
I want to outsource and reducing my code into components,
so my code is clean, readable and easy to re-use.

## Description

Refactoring the code into components for a better overview and understanding

## Acceptance criteria

- [ ] everything should work as expected after refactoring

## Tasks

- [ ] create branch "ref/code-refactoring"
- [ ] create some components (for example: the drop downs for the form)
- [ ] avoid everything that's unnecessary (spaghetti-code, redundant code)

**Comment by F-Kirchhoff** [comment]
Hey Jana,
can you please give a bit more detail what you want to refactor (the form / the component structure, styling)? Please keep in mind that the PR should not be too big, you can always create 2 PRs for the refactoring
