### ISSUE TITLE
Developer Story - refactoring function

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#29]
## Description

Trying to fixing some function- bugs I found, recently.

My most complex function, unfortunately, doesn't work as hoped, and some adjustments need to be made in the way the ingredients are retrieved and compared with health information.

## Acceptance criteria

- [ ] Everything should be working as expected
- [ ] the food ingredients should now be correctly compared with the cat health informations

## Tasks

- [ ] create a new branch named "bugfix"
- [ ] The function needs to be adjusted by breaking the strings into individual words. 
- [ ] Then, the manner in which the words are compared with the transmitted information of the cat needs to be revised.
- [ ] If possible, not too much should be rewritten so that readability and comprehensibility are not reduced.
