### ISSUE TITLE
US 3 - Add a new cat

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#3]
## Value proposition

As a cat owner/user,
I would like to add and display a new cat,
so that I always have an up-to-date overview of my cats.

## Description

![Bildschirmfoto 2023-08-14 um 15 05 23](https://github.com/JanaS87/capstone-project/assets/136725332/aefdfc80-8d0a-43d6-aabc-528ddf0789e5)

## Acceptance criteria

Cat Overview
- [ ] the new cat button redirects to the new cat page
- [ ] after saving the new cat it will be displayed in the overview
- [ ] clicking on the new listed cat will redirect to its profile page

New Cat
- [ ] every input field is useable
- [ ] the drop down menus allow the cat food search and list the found food options
- [ ] with the add buttons the selected food is added
- [ ] the back button leads back to the cat overview
- [ ] the save button saves the data and leads back to the overview

## Tasks

Cat Overview
- [ ] add "new cat" button and add dynamic routing with <Link /> to the new cat page

New Cat
- [ ] create a new component named "NewCatForm"
- [ ] create the needed label input fields and drop down menus in the component
- [ ] create a new page named "NewCat"
- [ ] insert the component into the page
- [ ] add the "add", "back" and "save" buttons to the page
- [ ] create the onClick functionality for the Save button (onSubmit)
- [ ] create the onClick functionality for the other buttons
- [ ] create the useState() to save the cat data into the existing cat array

**Comment by izabelladobielewska** [comment]
Hi Jana, every bit looks airtight :) I just have one question regarding the the Save button: where would you want to save the new cat data? Is it local? or will it be stored externally for the user to see it after logging in? Maybe this could be a feature for the next User Story? 🤔

**Comment by JanaS87** [comment]
Hey Izabella, thank you for the review and your question! The stored cat data is written back into the array using useState(). Later, the whole thing is to run via a database. Until then it will be created locally.
I forgot to write the useState into the tasks as well =/
