### ISSUE TITLE
Developer Story - Unit Testing

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#31]
## Description

Just some Unit Tests to proof, that the code runs as expected.
Especially my recommend- function. That's a big boi 😅 

## Acceptance criteria

Every test should be successfully run through.

## Tasks

- [x] create a new branch named "unit-testing"
- [ ] create the file recommendations.test.js
- [ ] write the needed tests, especially for the ingredients and the health issues (comparing each other to recommend or not recommend food)
