### ISSUE TITLE
US4- Food Search 

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#5]
## Value proposition

As a cat owner/user, 
I want to be able to search for a specific food and have it listed, 
so I know if my cats have had this food before.

## Description

![Food_Search](https://github.com/JanaS87/capstone-project/assets/136725332/5c01e704-47ad-4a96-8d9d-ade687cc212d)

## Acceptance criteria

- [ ] the food search can be found below the cat listing
- [ ] the search field should be visible
- [ ] all available cat food is displayed as a card
- [ ] it should be possible to enter a term in the search field
- [ ] when a term is entered into the search bar, the appropriate food is determined and displayed
- [ ] when the term is deleted from the search bar, all available cat food is displayed again

## Tasks

- [x] create a new branch named feat/food-search
- [x] create the array with the needed catfood data and name it “catfooddata.js”
- [x] create a new component for the CatFoodList
- [x] create a new component for the CatFoodCard
- [x] map over the data and create for each CatFood a card
- [x] add a Heading "Food Search" below the cat listing
- [x] create the search bar with an input field 
- [x] add a maximum character count
- [x] create a useState() and an onChange event for the search bar functionality
- [x] add the filter method to filter the food for the entered term
- [x] add styling

**Comment by mbosselmann** [comment]
Hi Jana,
LGTM! Just in case you think that this US is still too huge you could split the display of the cat food list and the search functionality in two separate US. Something I forgot to mention before. :) Nevertheless, I will approve this US as I think you can handle this. 👍 
Happy hacking! :octocat:

**Comment by FabianRuettgers** [comment]
Hey, your Feature looks great.

Here are some suggestions you might want to keep in mind:
- I can input only numbers as the pet name, you might want to change the input to (type="text")
- The Age can be set to -1, you might want to add min="0"
- Good Acceptance and bad Acceptance can be set to the same, which I guess shouldn't be able
- Your search filter needs a perfect match to filter, you might want to search for the same letters (https://www.w3schools.com/howto/howto_js_filter_lists.asp)
- Also on the List page, you got "Your Cats" as a h1 and after that, you have the Cats-name as a h3, you should change that for a semantic structure.
