### ISSUE TITLE
US5 - Navigation and Food Search page

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#6]
## Value proposition

As a cat owner/user,
I want to switch comfortably between the pages via the navigation bar,
so that the desired one is displayed to me.

## Description

![Navigation](https://github.com/JanaS87/capstone-project/assets/136725332/db15cbfb-8592-4ad4-9168-a7ecc6cdfb8e)

## Acceptance criteria

navigation
- [ ] the navigation bar leads to the food search page and from there also back again
- [ ] the active and inactive navbar icons are precisely identifiable by color

food search page
- [ ] the search field should be visible
- [ ] all available cat food is displayed as a card
- [ ] it should be possible to enter a term in the search field
- [ ] when a term is entered into the search bar, the appropriate food is determined and displayed
- [ ] when the term is deleted from the search bar, all available cat food is displayed again

## Tasks

navigation
- [x] create a new component “Navbar.js”
- [x] add and set the dynamic routing with <Link/> from the overview to the food search page and vice versa
- [x] use some nice icons from fontawesome for the navbar
- [x] add the navbar to the pages (overview and food search)
- [x] add styling

food search page
- [x] create a new page named FoodSearchPage.js
- [x] fill the page with the food page logic from the overview page
- [x] add (fill) styling

**Comment by DorisW3** [comment]
Dear Jana,
in "value proposition" please add a break after "navigation bar" for a better reading ;-)
In line "all available cat food is displayed as a card" maybe you can replace "card" with "tag". There is nothing else shown but the food name and i think "tag" is more specific ("card maybe suggests that there more information").
Everything else is fine! :-)
