### ISSUE TITLE
US6 - Food Details page

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-project#9]
## Value proposition

As a cat owner/user,
I want to click on a food and see all its details, 
so I know what ingredients this food has and which cat likes/dislikes it.

## Description

![Food_Details_page](https://github.com/JanaS87/capstone-project/assets/136725332/0ba892a3-66d2-4da7-a639-5978e4d4934b)

## Acceptance criteria

Food Search page
- [ ] food is clickable and leads to the Details page
- [ ] when hovering over the food names with the mouse,
       the color of the respective item changes

Food Details page
- [ ] every information is fully readable and visible
- [ ] the back button leads back to the food search page

## Tasks

Food Search page
- [x] create new branch and name it “feat/food-details-page”
- [x] add dynamic routing from the chosen cat food to the cat food details page with <Link>
- [x] add  styling (hover)

Food Details page
- [x] create new folder "foods" and inside of the folder a file named "[id].js"
- [x] create the heading
- [x] create the necessary lists for the respective information
- [x] map over the respective lists to create the listItems
- [x] add the back button and set the routing- functionality
- [x] add styling

**Comment by ninaassmann** [comment]
I guess the details page should have a name like [slug].js or something like that, when you want to have dynamic route.
The [ ] brackets are important

**Comment by JanaS87** [comment]
Thank you for the hint :) I forgot to mention that the page will be named [id].js. There will be a separate folder for the food. Just like with the cat.

Will change it.

**Comment by Faibs7** [comment]
Good changes. LGTM

**Comment by Faibs7** [comment]
The function to display all information on the detail page with one click works great. When searching, you can currently only search for the name of the food. Should that searchbar work like that? Otherwise you could possibly search for salmon or flavors. 
LGTM
